language: node_js
node_js:
  - "10"
script:
  - npm run standard
  - npm run installAll
  - npm run test
  - npm run e2e
cache:
  directories:
    - ~/.npm
    - ~/.cache
branches:
  only:
    - master
    - Vladimir`s-branch
