version: '3'

services:
  api:
    build:
      context: qit-api
      dockerfile: Dockerfile-ruby
    command: bundle exec rails s -p 3005 -b '0.0.0.0'
    ports:
      - 3005:3005
    environment:
      - 'DOCKER=true'
      - 'QIT_API_DATABASE_USERNAME=postgres'
      - 'QIT_API_DATABASE_PASSWORD='
      - 'QIT_API_DATABASE_NAME=postgres'
      - 'QIT_API_DATABASE_HOST=db'
      - 'QIT_API_SECRET=QITROCKS!'

  db:
    image: library/postgres
    environment:
      - POSTGRES_USER=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    volumes:
      - search:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - ELASTIC_PASSWORD=QITROCKS!
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Authorization
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: 'http://es01:9200'
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: QITROCKS!

  indexer:
    build:
      context: ./indexer

volumes:
  search:
    driver: local
  db:
    driver: local
